### ISSUE TITLE
Portal not found with posgres protocol

### ISSUE THREAD

**Issue by MarinPostma** [libsql/sqld#292]
Now we're on to another error, but this time it's on the side of PostgreSQL / [Postgres.js](https://github.com/porsager/postgres) 🤔

```

> postgres-js-sqld@1.0.0 start /home/runner/work/postgres-js-sqld/postgres-js-sqld
> tsx index.ts


node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^
PostgresError: Portal not found for name: "esjwzbwi1c81"
    at ErrorResponse (file:///home/runner/work/postgres-js-sqld/postgres-js-sqld/node_modules/.pnpm/postgres@3.3.4/node_modules/postgres/src/connection.js:769:26)
    at handle (file:///home/runner/work/postgres-js-sqld/postgres-js-sqld/node_modules/.pnpm/postgres@3.3.4/node_modules/postgres/src/connection.js:472:6)
    at Socket.data (file:///home/runner/work/postgres-js-sqld/postgres-js-sqld/node_modules/.pnpm/postgres@3.3.4/node_modules/postgres/src/connection.js:313:9)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at cachedError (file:///home/runner/work/postgres-js-sqld/postgres-js-sqld/node_modules/.pnpm/postgres@3.3.4/node_modules/postgres/src/query.js:171:23)
    at new Query (file:///home/runner/work/postgres-js-sqld/postgres-js-sqld/node_modules/.pnpm/postgres@3.3.4/node_modules/postgres/src/query.js:36:24)
    at sql (file:///home/runner/work/postgres-js-sqld/postgres-js-sqld/node_modules/.pnpm/postgres@3.3.4/node_modules/postgres/src/index.js:111:11)
    at <anonymous> (/home/runner/work/postgres-js-sqld/postgres-js-sqld/index.ts:5:7)

Node.js v18.14.2
```

The file: https://github.com/karlhorky/postgres-js-sqld/blob/main/index.ts

```ts
import postgres from 'postgres';

const sql = postgres({ host: '127.0.0.1' });
```

_Originally posted by @karlhorky in https://github.com/libsql/sqld/issues/288#issuecomment-1466033862_

**Comment by MarinPostma** [comment]
we don't support pgwire anymore.
